### ISSUE TITLE
RedundancyGroup summary is not correctly aligned

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#1222]
## Describe the bug
The summary should be on the right-hand side, near the timestamp.

```css 
.object-statistics {
  justify-self: end; // this rule having no effect
}
```

Tested Browsers:
Firefox ❌ 
Safari ❌ 
Chrome ✅ 
Brave ✅ 

## To Reproduce
Open the redundancy group detail view.

## Screenshots:

<img width="1068" alt="Image" src="https://github.com/user-attachments/assets/1a11344b-3d7c-4a7f-937b-af096b80b54b" />

<img width="343" alt="Image" src="https://github.com/user-attachments/assets/0fc28146-c677-46c5-b03c-215b9ef596d5" />

## Additional context
In the `.compact-layout` view, the summary in Safari is cropped.
