### ISSUE TITLE
Confusing display of downtime that ended normally in history

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb-web#691]
## Describe the bug

Downtimes that ended normally are displayed as "Downtime cancelled" in the history view which is confusing.

## To Reproduce

1. Schedule a fixed downtime and let it expire.
2. Open the history view.
3. Observe the event shown as "Downtime cancelled"

## Expected behavior
The event should use a more appropriate text like "Downtime ended"

## Screenshots

Downtime that ended normally:
![20221213_16h46m33s_grim](https://user-images.githubusercontent.com/18552/207379419-807cdf8a-7e9b-45b6-aed2-6973a04148b4.png)

Downtime that was manually cancelled:
![20221213_16h46m44s_grim](https://user-images.githubusercontent.com/18552/207379474-2eccf584-402b-4456-8f51-7690acf06824.png)

## Your Environment

Up-to-date `icinga/icingaweb2:master` Docker image (Digest: sha256:93e65f826b0d81cfa2c0c6150b11110942f00cf0050162eb9e99e1a7edeaad8a)

## Additional context

Data in the history tables looks fine, this is for an affected event:
```
MariaDB [icingadb]> SELECT * FROM history JOIN downtime_history ON downtime_history.downtime_id = history.downtime_history_id WHERE id = 0xe22281952d94f496fa619597aa82e8c358a20c88 \G
*************************** 1. row ***************************
                        id: 0xE22281952D94F496FA619597AA82E8C358A20C88
            environment_id: 0x6CC4013ECE4FFDBB275A4A763460507D17203146
               endpoint_id: 0x2BEA57085609682477BDE443BFF3E4081558CD15
               object_type: service
                   host_id: 0x2BEA57085609682477BDE443BFF3E4081558CD15
                service_id: 0x60524CEE41C45FB088F1432E8FF8B1650DBA81AC
   notification_history_id: NULL
          state_history_id: NULL
       downtime_history_id: 0x809EA1A32EC13328943171E0C623169DA01F9AAD
        comment_history_id: NULL
       flapping_history_id: NULL
acknowledgement_history_id: NULL
                event_type: downtime_end
                event_time: 1670946256000
               downtime_id: 0x809EA1A32EC13328943171E0C623169DA01F9AAD
            environment_id: 0x6CC4013ECE4FFDBB275A4A763460507D17203146
               endpoint_id: 0x2BEA57085609682477BDE443BFF3E4081558CD15
           triggered_by_id: NULL
                 parent_id: NULL
               object_type: service
                   host_id: 0x2BEA57085609682477BDE443BFF3E4081558CD15
                service_id: 0x60524CEE41C45FB088F1432E8FF8B1650DBA81AC
                entry_time: 1670946087707
                    author: icingaadmin
              cancelled_by: 
                   comment: x
               is_flexible: n
         flexible_duration: 0
      scheduled_start_time: 1670946136000
        scheduled_end_time: 1670946256000
                start_time: 1670946136000
                  end_time: 1670946256000
              scheduled_by: NULL
        has_been_cancelled: n
              trigger_time: 1670946136000
               cancel_time: 0
1 row in set (0.008 sec)
```
